---
- name: Installs fish
  become: true
  ansible.builtin.dnf:
    name: fish
    state: present

- name: Set fish as the default shell
  become: true
  ansible.builtin.user:
    name: "{{ user_name }}"
    shell: /usr/bin/fish

- name: Create a .config/fish directory if it does not exist
  ansible.builtin.file:
    path: "{{ user_home }}/.config/fish"
    state: directory
    mode: "0755"

- name: Symlink config.fish
  ansible.builtin.file:
    src: "{{ role_path }}/files/config.fish"
    dest: "{{ user_home }}/.config/fish/config.fish"
    state: link
