- name: Install touchegg
  become: yes
  apt:
    deb: "https://github.com/JoseExposito/touchegg/releases/download/2.0.11/touchegg_2.0.11_amd64.deb"

- name: Symlink .xprofile
  file:
    src: "{{ role_path }}/files/.xprofile"
    dest: "{{ user_home }}/.xprofile"
    state: link

- name: Create a touchegg config directory if it does not exist
  file:
    path: "{{ user_home }}/.config/touchegg"
    state: directory
    recurse: yes

- name: Check if touchegg.conf exists
  stat: path="{{ user_home }}/.config/touchegg/touchegg.conf"
  register: has_touchegg_conf
  failed_when: False

- name: Backup toucheegg.conf
  command: mv {{ user_home }}/.config/touchegg/touchegg.conf {{ user_home }}/.config/touchegg/touchegg.conf.bak
  when: has_touchegg_conf.stat.exists

- name: Symlink touchegg.conf
  file:
    src: "{{ role_path }}/files/touchegg.conf"
    dest: "{{ user_home }}/.config/touchegg/touchegg.conf"
    state: link