- name: Set up dotfiles
  hosts: local
  roles:
    - role: alacritty
    # - role: conky
    - role: i3
    - role: i3blocks
    - role: i3status
    - role: rofi
    - role: rofi_calc
    - role: streamdeck
    - role: tdrop
    - role: veracrypt
    - role: vscodium
