
- name: Create a i3status config directory if it does not exist
  file:
    path: "{{ user_home }}/.config/i3status"
    state: directory
    recurse: yes

- name: Check if i3status config file exists
  stat: path="{{ user_home }}/.config/i3status/config"
  register: has_i3status_config
  failed_when: False

- name: Backup i3status config file
  command: mv {{ user_home }}/.config/i3status/config {{ user_home }}/.config/i3status/config.bak
  when: has_i3status_config.stat.exists

- name: Symlink i3status config file
  file:
    src: "{{ role_path }}/files/config"
    dest: "{{ user_home }}/.config/i3status/config"
    state: link