#!/bin/bash

export GTK_USE_PORTAL=0
export MOZ_ENABLE_WAYLAND=1

export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway
export XDG_SESSION_TYPE=wayland

PATH=$PATH:~/.local/bin
PATH=$PATH:~/.nix-profile/bin

# startup keychain
eval "keychain --eval --quiet"

if ! which nvidia-smi ; then
    echo "nouveau drivers"
    exec nixGL -- sway
else
    echo "nvidia drivers"
    exec nixGL -- sway --unsupported-gpu
fi