
- name: Install i3blocks
  become: yes
  apt:
    name: i3blocks
    state: present

- name: Create a i3blocks config directory if it does not exist
  file:
    path: "{{ config_directory }}"
    state: directory
    recurse: yes

- name: Check if i3blocks config file exists
  stat: path="{{ config_directory }}/config"
  register: has_i3blocks_config
  failed_when: False

- name: Backup i3blocks config file
  command: mv {{ config_directory }}/config {{ config_directory }}/config.bak
  when: has_i3blocks_config.stat.exists

- name: Symlink i3blocks config file
  file:
    src: "{{ role_path }}/files/config"
    dest: "{{ config_directory }}/config"
    state: link

- name: Import i3blocks-contrib repo
  git:
    repo: https://github.com/vivien/i3blocks-contrib
    dest: "{{ config_directory }}/i3blocks-contrib"