
- name:  Add python asdf plugin
  command: asdf plugin add python
  register: result
  failed_when: result.rc != 0 and not (result.stderr is search("Plugin named python already added"))

- name: Installs needed apt packages
  become: yes
  loop: "{{ packages }}"
  apt:
    name: "{{ item }}"
    state: present

- name:  Install latest python version
  command: asdf install python latest

- name:  Set python version
  command: asdf global python latest