
- name: Install i3
  become: yes
  apt:
    name: i3
    state: present

- name: Install xss-lock to lock on lid close
  become: yes
  apt:
    name: xss-lock
    state: present

- name: Create a i3 config directory if it does not exist
  file:
    path: "{{ user_home }}/.config/i3"
    state: directory
    recurse: yes

- name: Check if i3 config file exists
  stat: path="{{ user_home }}/.config/i3/config"
  register: has_i3_config
  failed_when: False

- name: Backup i3 config file
  command: mv {{ user_home }}/.config/i3/config {{ user_home }}/.config/i3/config.bak
  when: has_i3_config.stat.exists

- name: Symlink i3 config file
  file:
    src: "{{ role_path }}/files/config"
    dest: "{{ user_home }}/.config/i3/config"
    state: link