#!/usr/bin/bash

MINUTES_TO_HIBERNATION=10

function hibernateInX() {
  echo "PID: $$"

  local wake_date
  wake_date=$(date -d+"$MINUTES_TO_HIBERNATION"minute +%s)
  rtcwake -m no -l -t "$wake_date"

  echo "Suspending $(date)"
  #systemctl start suspend.target
  /lib/systemd/systemd-sleep suspend

  local now_date
  now_date=$(date +%s)
  echo "Waking..."

  if [ "$now_date" -ge "$wake_date" ]; then
    echo "Hibernating..."
    #systemctl hibernate
    /lib/systemd/systemd-sleep hibernate
  fi

  echo "Done..."
}  

hibernateInX