[Sleep]
# MemorySleepMode= was removed in this config to test how systemd handles it with the defaults
# if sleep is inconsistent, enable this again
AllowSuspendThenHibernate=yes
HibernateDelaySec=20min
