
- name: Install xinput
  become: yes
  apt:
    name: xinput
    state: present

- name: Install xdotool
  become: yes
  apt:
    name: xdotool
    state: present

- name: Install libinput-tools
  become: yes
  apt:
    name: libinput-tools
    state: present

- name: Import libinput-gestures repo
  git:
    repo: https://github.com/bulletmark/libinput-gestures.git
    dest: "{{ user_home }}/.libinput-gestures"
    version: "2.72"

- name: Install libinput-gestures
  make:
    chdir: "{{ user_home }}/.libinput-gestures"
    target: install
  become: yes

- name: Check if libinput-gestures.conf exists
  stat: path="{{ user_home }}/.config/libinput-gestures.conf"
  register: has_libinput_gestures_conf
  failed_when: False

- name: Backup libinput-gestures.conf
  command: mv {{ user_home }}/.config/libinput-gestures.conf {{ user_home }}/.config/libinput-gestures.conf.bak
  when: has_libinput_gestures_conf.stat.exists

- name: Symlink libinput-gestures.conf
  file:
    src: "{{ role_path }}/files/libinput-gestures.conf"
    dest: "{{ user_home }}/.config/libinput-gestures.conf"
    state: link

- name: Add user to input groups
  shell: "gpasswd -a {{ user_name }} input"
  become: yes

- name: Symlink .xprofile
  file:
    src: "{{ role_path }}/files/.xprofile"
    dest: "{{ user_home }}/.xprofile"
    state: link
