---
- name: Install vim packages
  become: true
  ansible.builtin.dnf:
    name: "{{ vim_packages }}"
    state: present

- name: Symlink .vimrc
  ansible.builtin.file:
    src: "{{ role_path }}/files/.vimrc"
    dest: "{{ user_home }}/.vimrc"
    state: link
    force: true

- name: Symlink nvim
  ansible.builtin.file:
    src: "{{ role_path }}/files/nvim"
    dest: "{{ user_home }}/.config/nvim"
    state: link
    force: true
