- name: Add udev rules
  become: true
  ansible.builtin.command: "sh {{ role_path }}/files/udev.sh"
  changed_when: false

- name: Install streamdeck_ui
  ansible.builtin.command: "nix profile install nixpkgs#streamdeck-ui"
  changed_when: false

- name: Symlink icons
  become: true
  ansible.builtin.file:
    src: "{{ role_path }}/files/icons"
    dest: /usr/share/icons/streamdeck
    state: link
    force: true

- name: Ensure .config/systemd/user exists
  ansible.builtin.file:
    path: "{{ user_home }}/.config/systemd/user"
    state: directory
    recurse: true

- name: Symlink streamdeck.path
  ansible.builtin.file:
    src: "{{ role_path }}/files/streamdeck.path"
    dest: "{{ user_home }}/.config/systemd/user/streamdeck.path"
    state: link

- name: Create streamdeck.service
  ansible.builtin.copy:
    dest: "{{ user_home }}/.config/systemd/user/streamdeck.service"
    content: |
      [Unit]
      Description=Streamdeck Service

      [Service]
      Type=simple
      ExecStart=/home/{{ user_name }}/.local/bin/streamdeck -n
      Restart=on-failure

      [Install]
      WantedBy=default.target
    mode: u=rwx

- name: Make sure streamdeck.path is running
  ansible.builtin.systemd:
    name: streamdeck.path
    state: started
    enabled: true
    scope: user
