
- name: Import alacritty repo
  git:
    repo: https://github.com/alacritty/alacritty.git
    dest: "{{ user_home }}/.alacritty"

- name: Installs needed apt packages
  become: yes
  loop: "{{ packages }}"
  apt:
    name: "{{ item }}"
    state: present

- name: Build alacritty
  command: 
    cmd: cargo build --release
    chdir: "{{ user_home }}/.alacritty"

- name: Install terminfo
  become: yes
  command: 
    cmd: tic -xe alacritty,alacritty-direct extra/alacritty.info
    chdir: "{{ user_home }}/.alacritty"

- name: Move bin to /usr/local/bin
  become: yes
  command: 
    cmd: cp target/release/alacritty /usr/local/bin
    chdir: "{{ user_home }}/.alacritty"

- name: Move logo to pixmaps
  become: yes
  command: 
    cmd: cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
    chdir: "{{ user_home }}/.alacritty"

- name: Install desktop file
  become: yes
  command: 
    cmd: desktop-file-install extra/linux/Alacritty.desktop
    chdir: "{{ user_home }}/.alacritty"

- name: Update desktop database
  become: yes
  command: 
    cmd: update-desktop-database
    chdir: "{{ user_home }}/.alacritty"

- name: Create man1 directory for manual page
  become: yes
  file:
    path: /usr/local/share/man/man1
    state: directory

- name: Send alacritty.man to man
  become: yes
  shell: 
    cmd: gzip -c {{ user_home }}/.alacritty/extra/alacritty.man > /usr/local/share/man/man1/alacritty.1.gz
    chdir: "{{ user_home }}/.alacritty"

- name: Send alacritty-msg.man to man
  become: yes
  shell: 
    cmd: gzip -c {{ user_home }}/.alacritty/extra/alacritty-msg.man > /usr/local/share/man/man1/alacritty-msg.1.gz
    chdir: "{{ user_home }}/.alacritty"

