- name: Import alacritty repo
  ansible.builtin.git:
    repo: https://github.com/alacritty/alacritty.git
    dest: "{{ current_directory }}"
    version: master

- name: Installs needed apt packages
  become: true
  loop: "{{ packages }}"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  changed_when: false

- name: Build alacritty
  ansible.builtin.command:
    cmd: cargo build --release
    chdir: "{{ current_directory }}"
  changed_when: false

- name: Install terminfo
  become: true
  ansible.builtin.command:
    cmd: tic -xe alacritty,alacritty-direct extra/alacritty.info
    chdir: "{{ current_directory }}"
  changed_when: false

- name: Copy bin to /usr/local/bin
  become: true
  ansible.builtin.copy:
    src: "{{ current_directory }}/target/release/alacritty"
    dest: /usr/local/bin/alacritty
    mode: u=rwx,g=rx,o=rx

- name: Move logo to pixmaps
  become: true
  ansible.builtin.copy:
    src: "{{ current_directory }}/extra/logo/alacritty-term.svg"
    dest: /usr/share/pixmaps/Alacritty.svg
    mode: u=rw,g=r,o=r

- name: Install desktop file
  become: true
  ansible.builtin.command:
    cmd: desktop-file-install extra/linux/Alacritty.desktop
    chdir: "{{ current_directory }}"
  changed_when: false

- name: Update desktop database
  become: true
  ansible.builtin.command:
    cmd: update-desktop-database
    chdir: "{{ current_directory }}"
  changed_when: false

- name: Create man1 directory for manual page
  become: true
  ansible.builtin.file:
    path: /usr/local/share/man/man1
    state: directory
    mode: u=rwx,g=r,o=r

- name: Send alacritty.man to man
  become: true
  ansible.builtin.shell:
    cmd: gzip -c {{ current_directory }}/extra/man/alacritty.1.scd > /usr/local/share/man/man1/alacritty.1.gz
    chdir: "{{ current_directory }}"
  changed_when: false

- name: Send alacritty-msg.man to man
  become: true
  ansible.builtin.shell:
    cmd: gzip -c {{ current_directory }}/extra/man/alacritty-msg.1.scd > /usr/local/share/man/man1/alacritty-msg.1.gz
    chdir: "{{ current_directory }}"
  changed_when: false

- name: Creates alacritty conf directory if not exists
  ansible.builtin.file:
    path: "{{ alacritty_conf_dir }}"
    state: directory
    mode: u=rwx,g=r,o=r

- name: Check if alacritty.yml exists
  ansible.builtin.stat:
    path: "{{ alacritty_conf }}"
  register: has_alacritty_yml
  failed_when: false

- name: Backup alacritty.yml
  ansible.builtin.command: mv {{ alacritty_conf }} {{ alacritty_conf }}.bak
  when: has_alacritty_yml.stat.exists

- name: Symlink alacritty.yml
  ansible.builtin.file:
    src: "{{ role_path }}/files/alacritty.yml"
    dest: "{{ alacritty_conf }}"
    state: link
