---
- name: Install veracrypt GUI
  ansible.builtin.command:
    cmd: sg nix-users -c 'nix profile add --impure nixpkgs#veracrypt'
    creates: "{{ user_home }}/.nix-profile/bin/veracrypt"
  environment:
    NIXPKGS_ALLOW_UNFREE: "1"
