---
- name: Install zellij
  ansible.builtin.command:
    cmd: sg nix-users -c 'nix profile add nixpkgs#zellij'
    creates: "{{ user_home }}/.nix-profile/bin/zellij"

- name: Ensure .config/zellij exists
  ansible.builtin.file:
    path: "{{ user_home }}/.config/zellij"
    state: directory
    mode: "0755"

- name: Symlink zellij config files
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ user_home }}/.config/zellij/{{ item | basename }}"
    state: link
    force: true
  with_fileglob:
    - "{{ role_path }}/files/*"
