---
- name: Create the fonts directory
  ansible.builtin.file:
    path: "{{ fonts_directory }}"
    state: directory
    mode: "0755"

- name: Copy fonts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ fonts_directory }}/"
    mode: "0644"
  with_fileglob:
    - "{{ role_path }}/files/*"
  notify: Regenerate font cache
